export const SPELLS = [
  {id:'tinder',name:'Tinder',level:1,school:'Ember',icon:'flame',color:'#f1ad62',mana:9,cooldown:1.25,power:23,type:'attack',range:24,invocation:'Goddess of fire, lend me a spark to keep the darkness far.',anchors:['fire','spark'],description:'A small, precise flame. Cheap to cast and exceptionally responsive to refinement.',lore:'A hearth spell older than the academy. A master can thread it through a knight’s visor without warming the steel.',unlock:'Known from the beginning.'},
  {id:'mend',name:'Mend',level:1,school:'Tide',icon:'droplet',color:'#86d8bb',mana:18,cooldown:6,power:32,type:'heal',range:14,invocation:'Waters of memory, gather what was broken and make it whole.',anchors:['waters','whole'],description:'Restore vitality. Mends the wounded courier when she is near.',lore:'Restores a living pattern; it cannot resurrect a lost consciousness.',unlock:'Known from the beginning.'},
  {id:'stoneward',name:'Stoneward',level:1,school:'Stone',icon:'shield',color:'#d7c794',mana:17,cooldown:6,power:34,type:'shield',range:16,invocation:'Patient earth, stand between this fragile heart and harm.',anchors:['earth','harm'],description:'A six-second barrier. Absorbs damage before vitality is lost.',lore:'Earth is a metaphor for resistance. No elemental spirit needs to answer.',unlock:'Known from the beginning.'},
  {id:'gale',name:'Gale',level:2,school:'Breath',icon:'wind',color:'#a9e8da',mana:20,cooldown:4,power:31,type:'push',range:24,invocation:'Wandering wind, unbind the still air and carry my will.',anchors:['wind','will'],description:'Repel enemies and interrupt a charging attack.',lore:'Couriers originally used this pattern to push rain away from wet ink.',unlock:'Awaken the three waylights.'},
  {id:'emberlance',name:'Ember Lance',level:2,school:'Ember',icon:'flame',color:'#fa875d',mana:25,cooldown:3.5,power:48,type:'attack',range:32,invocation:'Goddess of fire, gather your scattered embers into a single spear.',anchors:['fire','spear'],description:'A long-range bolt. More force than Tinder, with a much higher mana cost.',lore:'The familiar academy demonstration spell. Power is easy to notice; efficiency is easy to miss.',unlock:'Awaken the three waylights.'},
  {id:'rime',name:'Rime',level:2,school:'Tide',icon:'snowflake',color:'#b6e0ef',mana:22,cooldown:5,power:35,type:'slow',range:27,invocation:'Waters beneath winter, remember stillness and hold your breath.',anchors:['winter','stillness'],description:'Crystallize moisture around an enemy, slowing it for four seconds.',lore:'A fisher’s preservation pattern adapted by frontier wardens.',unlock:'Prove yourself at the academy, or join the Unbound Road.'},
  {id:'flameedge',name:'Flame Edge',level:3,school:'Ember',icon:'sword',color:'#eea877',mana:30,cooldown:14,power:20,type:'enchant',range:0,invocation:'Goddess of fire, dwell upon this steel and follow its edge.',anchors:['fire','steel'],description:'Imbue your blade for sixteen seconds. Enchantment is rare among novices.',lore:'Holding a moving pattern is harder than releasing one. Elian teaches it only after the grove is safe.',unlock:'Clear the grove, then ask Elian about enchantment.'},
  {id:'thunder',name:'Thunder',level:3,school:'Breath',icon:'zap',color:'#d8bcf5',mana:34,cooldown:6,power:69,type:'attack',range:30,invocation:'Sky without borders, let the distance between us become thunder.',anchors:['sky','distance'],description:'A concentrated discharge that deals heavy damage to one target.',lore:'A loud report is a consequence, never the source of its power.',unlock:'Return the watchtower record to your mentor.'},
  {id:'starfall',name:'Starfall',level:4,school:'Aether',icon:'star',color:'#eedda4',mana:48,cooldown:10,power:100,type:'area',range:30,invocation:'Light beyond the veil, descend as a fragment of the first dawn.',anchors:['light','dawn'],description:'A falling aether fragment damages enemies around your target.',lore:'A miniature construction of a star, not a celestial body pulled from the heavens.',unlock:'Recover the Bellkeeper’s memory.'},
  {id:'river',name:'Returning River',level:5,school:'Tide',icon:'droplet',color:'#86d8bb',mana:70,cooldown:18,power:0,type:'future',invocation:'Waters of the thousand paths, return this borrowed life to its own course.',anchors:['waters','life'],description:'Restore several living allies across a battlefield.',lore:'Rare military medicine. Cannot reverse death or restore a destroyed mind.',unlock:'Beyond Chapter I.'},
  {id:'citadel',name:'Living Citadel',level:6,school:'Stone',icon:'shield',color:'#d7c794',mana:120,cooldown:30,power:0,type:'future',invocation:'Patient earth, remember every shelter and raise a home against the storm.',anchors:['earth','shelter'],description:'A sustained defensive enclosure that changes with incoming force.',lore:'Used by B-rank disaster teams. Keeping it stable demands more skill than creating it.',unlock:'Beyond Chapter I.'},
  {id:'sun',name:'Second Sun',level:7,school:'Ember',icon:'sun',color:'#ffc86d',mana:200,cooldown:60,power:0,type:'future',invocation:'Goddess of fire, witness the oath I carry and let dawn answer once again.',anchors:['fire','dawn'],description:'A controlled field of radiant heat. The practical ceiling for most endgame casters.',lore:'An A-rank feat when performed safely. Its danger is collateral heat, not an arbitrary damage number.',unlock:'Beyond Chapter I.'},
  {id:'horizon',name:'Horizon Fold',level:8,school:'Aether',icon:'orbit',color:'#d2bbef',mana:350,cooldown:90,power:0,type:'future',invocation:'Distance that divides all things, borrow my horizon and surrender your own.',anchors:['distance','horizon'],description:'Briefly join two prepared points through folded space.',lore:'S-rank research remains incomplete in the Low World. The Ascendant Reach teaches it as infrastructure.',unlock:'The Ascendant Reach — future realm.'},
  {id:'choir',name:'Thousandfold Choir',level:9,school:'Aether',icon:'sparkles',color:'#c8eeea',mana:600,cooldown:180,power:0,type:'future',invocation:'Voices before memory, keep each borrowed name distinct within my mind.',anchors:['voices','mind'],description:'Sustain many independent magical patterns without merging their identities.',lore:'SS-adjacent magic. Parallel casting is its prerequisite, not its automatic reward.',unlock:'The Ascendant Reach — future realm.'},
  {id:'firstword',name:'First Word',level:10,school:'Aether',icon:'star',color:'#fff2ca',mana:1000,cooldown:300,power:0,type:'future',invocation:'World that remembers, hear a word you have never known.',anchors:['world','word'],description:'A disputed theoretical pattern that would alter a local law of magic.',lore:'No verified mortal casting exists. Level 10 is a spell category; it does not create an SSS adventurer rank.',unlock:'World lore only. Not a playable ability.'}
];
export const SPELL_BY_ID = Object.fromEntries(SPELLS.map(s=>[s.id,s]));
export const HOTBAR = ['tinder','mend','stoneward','gale','emberlance','rime','flameedge','thunder','starfall'];
export const LOCATIONS = [
  {id:'village',name:'Bellwether',subtitle:'A town built around a missing sound',x:0,z:48,color:'#d7b672',kind:'Sanctuary',text:'Bread ovens share their embers each morning. Brass bells hang above every door, but none has rung since the stillness spread from the old observatory. The town survives by gathering moon flax, repairing caravan wards, and sheltering academy hopefuls.'},
  {id:'academy',name:'Lumen Academy',subtitle:'Knowledge is a privilege with a locked door',x:0,z:-33,color:'#a7ded9',kind:'Trials & study',text:'Founded after the Sundering to prevent careless magic from becoming civic disaster. Its entrance exams measure precision, protection, and composure. Only a handful enter each term. Rejected applicants may return with new experience and a clean record.'},
  {id:'grove',name:'The Hushwood',subtitle:'Where the forest has forgotten its own voice',x:61,z:5,color:'#98c8ba',kind:'Danger · E–D',text:'A coppice of blue-leafed trees sustained by old tide channels. Empty Echoes now feed on the mana carried through those roots. Foresters leave wind chimes on the trail; a silent chime means turn back.'},
  {id:'watchtower',name:'Northwatch Ruin',subtitle:'The last watch was never relieved',x:-60,z:-32,color:'#bdcbd5',kind:'Discovery',text:'A broken relay tower overlooking the vale. Its keeper recorded a sixth bell beneath the five public tolls. The academy filed her report as weather interference. Her journal is still upstairs among the fallen stones.'},
  {id:'crypt',name:'The Sunken Choir',subtitle:'An observatory beneath the roots',x:66,z:-62,color:'#ad93c8',kind:'Dungeon · D–C',text:'Before it became a tomb, the Choir measured resonances arriving from a realm above the sky. Its custodian preserved a voice by taking every sound around it. Fire wakes the mechanism, water names it, and stone remembers.'},
  {id:'gate',name:'The Fifth-Year Gate',subtitle:'An impossible door, almost awake',x:0,z:-101,color:'#e4c577',kind:'Chapter finale',text:'Three lost bell fragments can make the forgotten arch answer. It opens naturally once every five years. Beyond lies the Ascendant Reach, where S-rank strength is ordinary and everything the Low World calls extraordinary must be relearned.'},
  {id:'lake',name:'Mirrorwater',subtitle:'Some things are clearer in reflection',x:48,z:58,color:'#8ecdda',kind:'Rest & gathering',text:'The vale’s freshwater basin. Tiny aether organisms shine where the water is clean. Ilyra uses its reeds for tinctures; children say the lake reflects an extra moon on gate years.'}
];
export const NPCS = [
  {id:'ilyra',name:'Ilyra',title:'Keeper of the waylights',x:4,z:47,color:0x819d8b,hair:0xd8d9c0,greeting:'You arrived while the bells were sleeping. That makes two of us listening for something. There are three cold waylights on the academy road. Wake them with Tinder, if you know how. Ask me about magic, the waylights, or the town.'},
  {id:'examiner',name:'Provost Cael',title:'Lumen examiner',x:-6,z:-27,color:0x4e7186,hair:0xc2c5c4,greeting:'Potential is common. Restraint is not. The entrance examination measures precision, protection, and composure. Say you wish to apply when you are ready. I can also explain the trials, your record, or graduation.'},
  {id:'sera',name:'Sera Venn',title:'An unregistered wayfarer',x:-25,z:38,color:0x957e99,hair:0xc4bbb0,greeting:'I failed those gates twice. The trees never asked for my examination score. If you would rather learn on the road, tell me. You can also ask about the grove, the watchtower, or the gate.'},
  {id:'elian',name:'Elian',title:'Smith of quiet steel',x:-21,z:54,color:0xab8d69,hair:0x51443c,greeting:'A blade and a spell are tools. Anyone who tells you to choose just one is trying to sell you a uniform. Clear the Hushwood, and I might teach you an enchantment. Ask about weapons, refinement, or Flame Edge.'},
  {id:'merchant',name:'Neris',title:'Caravan apothecary',x:17,z:53,color:0x908a59,hair:0x785241,greeting:'A tonic costs twelve crowns. Say “buy a tonic” if you need one. Your first three are already in your satchel. I can tell you about trade or the roads, too.'},
  {id:'courier',name:'Tavi',title:'An injured courier',x:37,z:16,color:0x608d97,hair:0xe3c289,greeting:'The things in the grove took the sound right out of my warning. I made it this far. Could you mend this wound? The package is for the academy, but what I saw belongs to everyone.'}
];
export const CODEX = [
  {id:'premise',category:'World',title:'A world that remembers',subtitle:'The first principle',body:[
    'The world is called Vesper. Aether remembers stable patterns: heat, weight, motion, a living body. A caster uses mana to ask for one of those patterns again. Speech supplies its shape. The final declaration fixes the scale and the identity: “Level 1. Tinder.”',
    'Prayer is one language of magic, not proof that a god intervened. Invoking the Goddess of Fire is a reliable mnemonic inherited across generations. Spirits exist and may help, but no contract or bloodline is required to become a caster.',
    'The Lantern Vale sits at the edge of a world that mistakes its own limits for universal laws. Every five years, a hidden gate opens into the Ascendant Reach. Its people have spent centuries learning what the Low World has forgotten.'
  ]},
  {id:'history',category:'World',title:'The five silences',subtitle:'A short history of Vesper',body:[
    'Before the calendar: the First Choir built a network of observatories between the Low World and the Reach. The network transmitted knowledge as carefully contained resonance.',
    'Year 0, the Sundering: a choir tried to sustain a single shared mind across the network. Its patterns collided. Cities survived; the roads between realms did not. Records from before that moment contradict one another.',
    'Year 83: Lumen Academy received a charter to license public wardwork. In exchange, its examinations became independent of inherited wealth—at least on paper.',
    'Year 215: the Brass Compact standardized adventurer ranks. These describe reliable field capability, not moral worth, social status, or the level of a single spell.',
    'Year 430, the present: Bellwether has fallen quiet. The Fifth-Year Gate is due to open. A keeper beneath the vale is trying to preserve one voice at the expense of every other.'
  ]},
  {id:'magic',category:'Magic',title:'Invocation and declaration',subtitle:'The voice gives form; mana pays the cost',body:[
    'An invocation assembles a pattern. A declaration releases it. Novices need both. A practiced wording can vary, but it must preserve the invocation’s elemental intent and end in the correct level and name.',
    'Sages, a few reincarnated minds, and exceptionally rare casters can assemble a pattern without speaking the invocation. They must still say the declaration aloud. Incantationless casting is a tremendous achievement; it is not a beginner toggle.',
    'Spell levels run from 1 to 10. Most accomplished adventurers never need to exceed Level 7. Levels measure pattern complexity and scale. A refined Level 1 spell can outperform a crude higher-level spell.',
    'In this chapter, recognized invocation keywords represent enunciation and intent. Your browser’s transcript is not a scientific measurement of vocal power. Speaking clearly at an ordinary volume is sufficient. Assisted keyboard casts work at 65% potency.'
  ]},
  {id:'refinement',category:'Magic',title:'The hundred small corrections',subtitle:'Refinement',body:[
    'Refinement belongs to each spell, not to a character class. Using Tinder well makes Tinder more precise. Experience with a sword improves your swordwork. Your choices can cross any of these boundaries.',
    'At full refinement, a spell has four times its unrefined potency and costs less mana. A mastered Tinder can exceed an unrefined Ember Lance while remaining far cheaper. Practice against an inert focus helps only up to 30%; the rest must be learned in the field.',
    'Raw mana capacity determines how much pattern you can sustain. It does not supply judgment. A large reservoir in careless hands is a larger accident waiting to happen.'
  ]},
  {id:'schools',category:'Magic',title:'The five working languages',subtitle:'Disciplines without classes',body:[
    'Ember changes energy: hearths, light, controlled heat, destructive release. Tide preserves and redirects living or fluid patterns. Stone negotiates weight, structure, and resistance. Breath changes motion, pressure, and charge. Aether works on the relations between the others.',
    'A physical fighter can learn body reinforcement. A scholar can carry a blade. Enchantments bind magic to a moving object and are therefore uncommon among beginners. Mastering several disciplines takes time, not a class change.',
    'Spirits are independent patterns with memory and will. A pact can teach unfamiliar structures or share a burden. It can also create obligations. None is required for ordinary spellcraft.'
  ]},
  {id:'parallel',category:'Magic',title:'Two thoughts held apart',subtitle:'Parallel casting · later progression',body:[
    'Parallel casting sustains distinct patterns at the same time. Alternating quickly between spells is not parallel casting. Neither is releasing one spell that contains several effects. Released wards and enchantments can persist together; that is different from constructing and sustaining several independent patterns at once.',
    'Each active pattern consumes attention as well as mana. Failure can merge them, collapse them, or redirect a release. A caster must prove extraordinary control before learning the discipline.',
    'Neither parallel casting nor incantationless casting is unlocked in Chapter I. They remain meaningful future milestones. SSS is not an implemented rank.'
  ]},
  {id:'ranks',category:'Society',title:'What a letter can promise',subtitle:'The Brass Compact',body:[
    'E: registered novice, suitable for supervised local work. D: dependable against common frontier dangers. C: trusted with independent expeditions. B: a regional expert who can lead others through unusual threats.',
    'A: extraordinary even among professionals. Nations know these names. S: figures capable of changing a major conflict. SS: near the established mortal ceiling. The Compact recognizes no SSS rank.',
    'Ranks summarize repeatable capability under pressure. A specialist may surpass their rank in one narrow craft. The Reach changes the comparison: an S-rank visitor there encounters people of similar power doing ordinary work.'
  ]},
  {id:'academy',category:'Society',title:'The gates of Lumen',subtitle:'Admission, teaching, and consequence',body:[
    'Lumen accepts a handful of applicants each term. Three trials test precise release, protection under timed pressure, and composure in a live encounter. You can study before applying, and a failed attempt is never the end of the game.',
    'Accepted students receive a curriculum through graduation: tend an injured courier, clear the grove, recover the watchtower record, and resolve the disturbance beneath the vale. Graduation is awarded for field judgment, not attendance.',
    'Rejected or independent adventurers can learn from Sera and earn a Wayfarer seal. Reapplication is possible after further practice. Unresolved offenses block admission; paying restitution clears the active warrant, while the historical record remains.',
    'The opening lesson covers controls and the interface. The academy’s instruction is earned by admission. Outside its walls, knowledge comes from people, books, and experiments.'
  ]},
  {id:'factions',category:'Society',title:'Those who claim to keep order',subtitle:'Factions of the Low World',body:[
    'Lumen Collegium: researchers, examiners, healers, and licensed wardwrights. They fear another Sundering, sometimes more than they value the people their caution leaves outside.',
    'The Unbound Road: itinerant practitioners who share techniques without asking for a seal. Their independence protects unusual talent and makes consistent accountability difficult.',
    'The Brass Compact: caravan houses and adventurer registrars. Their currency is credible promises. A contract that cannot be understood by both parties is void under their charter.',
    'The Quiet Choir: custodians of old resonant machines. Some preserve memory. Others mistake preservation for the right to decide whose voice deserves to remain.',
    'The Glass Court: administrators of the Ascendant Reach. Its districts are maintained by S-rank workers. It considers the Low World a dangerous archaeological site, not a conquered province.'
  ]},
  {id:'atlas',category:'World',title:'Beyond the Lantern Vale',subtitle:'A continent with unfinished arguments',body:[
    'The Cinder March: geothermal terraces and fire-tempered foundries. Towns argue over the heat rights beneath their streets. Its greatest wardens use Level 2 magic with terrifying refinement.',
    'The Saltglass Coast: tidal cities connected by contracted passage. Healing houses refuse to recognize inherited rank. Smugglers trade fragments of banned pre-Sundering records.',
    'The Thorn Concord: forest settlements governed by negotiated agreements with local spirits. Consent matters here because a forest can remember a broken promise longer than a person can live.',
    'The White Expanse: high ice fields with auroral mana currents. Reincarnation stories cluster around its abandoned listening stations, but no theory explains every case.',
    'The Ascendant Reach: terraces above an artificial horizon, accessible through rare gates on five-year cycles. S is ordinary there; SS remains exceptional. Its inhabitants have political conflicts and everyday needs that power alone cannot solve.',
    'These regions belong to the larger setting. The Lantern Vale and Sunken Choir are the explorable regions in this first chapter.'
  ]},
  {id:'life',category:'Society',title:'Life between adventures',subtitle:'Bread, crowns, and borrowed fire',body:[
    'One crown buys a simple meal; twelve buy a concentrated field tonic. Towns maintain public wardstones because an unwarded caravan route makes every loaf more expensive.',
    'Ordinary people use specialized magic rather than adventurer combat. A baker may possess extraordinary refinement in a single heating pattern and no ability to fight at all.',
    'Children practice declarations using unpowered breathing games. Funerals include a last telling of a person’s name, followed by a silence no magic is allowed to fill.',
    'The year has five bell seasons. Gate years add a sixth night outside the civic calendar. Most towns treat it as a holiday. Bellwether now has reasons to be afraid of it.'
  ]},
  {id:'echoes',category:'Creatures',title:'The Empty Echoes',subtitle:'The price of stolen resonance',body:[
    'An Empty Echo is the outline left when a living pattern loses the memory that held it together. It seeks mana to repair itself, but cannot remember what it was trying to become.',
    'The Hushwood’s echoes resemble antlered animals and drifting lanterns. They are not evil by choice. Dissolving a hostile echo returns its borrowed mana to the environment.',
    'The Bellkeeper is different. Its mind remains, caught in a machine that preserves a single voice. Its attack patterns repeat the three duties it once had: call, shelter, and keep watch.'
  ]},
  {id:'people',category:'People',title:'The people of the vale',subtitle:'No one is merely a quest giver',body:[
    'Ilyra once maintained the academy’s emergency wards. She left after a rejected student died on a route the school had refused to teach. She tends waylights because useful knowledge should illuminate a road.',
    'Sera Venn failed Lumen twice: once for impatience, once for protecting another applicant during a timed test. She still carries her second score sheet. It has more corrections than numbers.',
    'Provost Cael believes exams save lives. His younger brother survived the failure of an unlicensed ward. He can learn to respect an independent practitioner without abandoning his duty.',
    'Elian’s hands no longer hold a complex invocation steady. He teaches moving patterns through swordwork and worries that the secret will die with him.',
    'Tavi is a courier because news should travel faster than rumor. Neris sells remedies but gives water freely. Both will notice whether you help before asking for payment.'
  ]},
  {id:'keeper',category:'People',title:'The voice beneath the bells',subtitle:'Read after the Sunken Choir',requires:'bossDefeated',body:[
    'The Bellkeeper was built to preserve the observatory’s records. During the Sundering, its last attendant asked it to remember her daughter’s voice. It interpreted that request as its highest instruction.',
    'For centuries it kept that one recording intact. Then its aether reservoir began to fail. It drew resonance from the roots, the animals, and finally the bells of Bellwether.',
    'When the three working patterns are restored, the custodian can release its burden. What remains in the final fragment is not a weapon or a prophecy. It is a child asking whether the stars can hear her.'
  ]},
];
export const RANKS = [{name:'E',xp:0,title:'Newly awakened'},{name:'D',xp:160,title:'Waylight bearer'},{name:'C',xp:440,title:'Vale warden'},{name:'B',xp:850,title:'Keeper of the crossing'}];
export const CONTROL_ROWS = [['W A S D / Arrow keys','Move'],['Right-drag / Q and E while no one is near','Turn camera'],['Mouse wheel','Zoom'],['Shift / Space','Dodge'],['F','Sword strike'],['E','Speak / interact'],['V','Start or stop voice casting'],['1–9','Assisted spell casts'],['R','Drink a tonic'],['Enter','Speak to a nearby person'],['M / J / K','Atlas / Journal / Grimoire'],['Esc','Pause / close a book']];
