import * as THREE from 'three';
import {NPCS} from './data.js';
import {SoftwareRenderer} from './software-renderer.js';
import {profile,batchScenery,batchActor} from './performance.js';
import {OutlineEffect} from 'three/addons/effects/OutlineEffect.js';
import {createCharacter,createCreature,createHouse,createNature,createSky,addWorldDetail,castSigil} from './art-direction.js';
const TAU=Math.PI*2;
export function rng(seed=430){let a=seed;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
export class WorldScene {
 constructor(canvas,quality='high'){
  this.scene=new THREE.Scene();this.scene.fog=new THREE.FogExp2(0xa5c9d9,.0036);this.scene.background=new THREE.Color(0x78b9dc);
  const context=canvas.getContext('webgl2',{antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer=context?new THREE.WebGLRenderer({canvas,context,antialias:true,alpha:false,powerPreference:'high-performance'}):new SoftwareRenderer(canvas);this.renderer.setPixelRatio(Math.min(window.devicePixelRatio,quality==='high'?1.65:1));this.renderer.shadowMap.enabled=quality==='high';this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.toneMapping=THREE.NoToneMapping;this.renderer.toneMappingExposure=1;this.renderer.outputColorSpace=THREE.SRGBColorSpace;
  this.camera=new THREE.PerspectiveCamera(52,1,.1,480);this.camera.position.set(9,8,72);this.camera.lookAt(0,2,53);
  this.matCache=new Map();this.inkCache=new Map();this.particleGeometry=new THREE.IcosahedronGeometry(.12,0);this.textures=new Map();this.banners=[];this.sigilEffects=[];
  const tones=new Uint8Array([88,155,212,255]);this.gradientMap=new THREE.DataTexture(tones,4,1,THREE.RedFormat);this.gradientMap.minFilter=this.gradientMap.magFilter=THREE.NearestFilter;this.gradientMap.needsUpdate=true;
  if(!this.renderer.isSoftwareRenderer)this.outline=new OutlineEffect(this.renderer,{defaultThickness:.0014,defaultColor:[.06,.12,.17],defaultAlpha:.72});
  this.collisions=[];this.npcs=[];this.objects=[];this.decorations=[];this.floaters=[];this.fx=[];this.random=rng();
  this.scene.add(new THREE.HemisphereLight(0xd9ecfa,0xa0b595,.85));
  const sun=new THREE.DirectionalLight(0xffe2b8,1.65);sun.position.set(-45,80,48);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-100;sun.shadow.camera.right=100;sun.shadow.camera.top=100;sun.shadow.camera.bottom=-100;sun.shadow.camera.far=220;sun.shadow.bias=-.0008;sun.shadow.normalBias=.035;this.scene.add(sun);
  const rim=new THREE.DirectionalLight(0x9cddef,.4);rim.position.set(40,20,-80);this.scene.add(rim);
  this.buildTerrain();this.buildWorld();addWorldDetail(this);this.buildNature();this.buildSky();this.player=this.character(0x466b73,0xe3d8c2,true);this.scene.add(this.player);this.player.position.set(0,0,57);
  this.optimization=this.renderer.isSoftwareRenderer?null:batchScenery(this);
  this.targetRing=this.ring(1.3,0xffdf99,.065);this.targetRing.visible=false;
  this.resize();
 }
 material(color,extra={}) {const {roughness,metalness,flatShading,...params}=extra;const key=JSON.stringify([color,params]);if(!this.matCache.has(key)){const m=new THREE.MeshToonMaterial({color,gradientMap:this.gradientMap,...params});m.userData.outlineParameters={visible:false,thickness:.0012};this.matCache.set(key,m);}return this.matCache.get(key);}
 surface(name,color=0xffffff,rx=1,ry=1){const key=`${name}-${rx}-${ry}`;if(!this.textures.has(key)){const tex=new THREE.TextureLoader().load(`/art/${name}.webp`);tex.colorSpace=THREE.SRGBColorSpace;tex.wrapS=tex.wrapT=THREE.MirroredRepeatWrapping;tex.repeat.set(rx,ry);tex.anisotropy=4;this.textures.set(key,tex);}const m=new THREE.MeshToonMaterial({color,map:this.textures.get(key),gradientMap:this.gradientMap});m.userData.outlineParameters={visible:false};return m;}
 inkMaterial(m){if(!this.inkCache.has(m.uuid)){const ink=m.clone();ink.userData.outlineParameters={visible:!m.transparent,thickness:.0014};this.inkCache.set(m.uuid,ink);}return this.inkCache.get(m.uuid);}
 configurePerformance(name='balanced'){this.performanceProfile=profile(name);this.resolutionScale=1;this.renderer.shadowMap.enabled=this.performanceProfile.shadows&&this.state?.settings.quality!=='low'&&!this.renderer.isSoftwareRenderer;this.renderer.shadowMap.autoUpdate=false;this.renderer.shadowMap.needsUpdate=true;if(this.outline)this.outline.enabled=name!=='battery';this.resize();}
 renderWorld(){if(this.renderer.shadowMap.enabled&&performance.now()-(this.lastShadow||0)>150){this.renderer.shadowMap.needsUpdate=true;this.lastShadow=performance.now();}if(this.outline)this.outline.render(this.scene,this.camera);else this.renderer.render(this.scene,this.camera);}
 castVisual(color,level=1){castSigil(this,this.player.position.x,this.player.position.z,color,level);this.castPose=1;}

 mesh(geo,color,x=0,y=0,z=0,extra={}) {const m=new THREE.Mesh(geo,this.material(color,extra));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;return m;}
 box(w,h,d,color,x=0,y=0,z=0){return this.mesh(new THREE.BoxGeometry(w,h,d),color,x,y,z);}
 cyl(r1,r2,h,color,x=0,y=0,z=0,n=8){return this.mesh(new THREE.CylinderGeometry(r1,r2,h,n),color,x,y,z);}
 ring(radius,color,width=.08,x=0,z=0) {const m=new THREE.Mesh(new THREE.RingGeometry(radius-width,radius,64),new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide,transparent:true,opacity:.9,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set(x,.06,z);this.scene.add(m);return m;}
 block(x,z,w,d,h=0){this.collisions.push({x,z,w:w/2+.38,d:d/2+.38,h});}
 buildTerrain(){
  const geo=new THREE.PlaneGeometry(300,300,100,100);geo.rotateX(-Math.PI/2);const a=geo.attributes.position,colors=[];const c=new THREE.Color();for(let i=0;i<a.count;i++){const x=a.getX(i),z=a.getZ(i);const noise=(Math.sin(x*.1)*Math.cos(z*.11)+1)*.5;c.setHSL(.25+noise*.025,.35+noise*.08,.49+noise*.035);colors.push(c.r,c.g,c.b);}geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));const ground=new THREE.Mesh(geo,this.surface('grass',0xffffff,85,85));ground.receiveShadow=true;this.scene.add(ground);
  const path=(pts,width=3)=>{for(let i=0;i<pts.length-1;i++){const a=pts[i],b=pts[i+1];const len=Math.hypot(b[0]-a[0],b[1]-a[1]);const m=this.box(width,.07,len+.5,0x9d9b83,(a[0]+b[0])/2,.04,(a[1]+b[1])/2);m.rotation.y=Math.atan2(b[0]-a[0],b[1]-a[1]);m.material=this.surface('road',0xffffff,width/3,len/3);m.castShadow=false;this.scene.add(m);}};
  path([[0,77],[0,-34]],4.6);path([[0,32],[26,25],[57,8],[66,-22],[66,-62]],3.2);path([[0,-6],[-30,-18],[-60,-32]],2.7);path([[0,-32],[27,-33],[29,-60],[17,-81],[0,-101]],3.2);path([[-33,48],[22,48]],3.5);path([[17,53],[36,67]],2.5);
  const plaza=this.cyl(15,15,.12,0xa8a997,0,.06,-22,48);plaza.material=this.surface('stone',0xffffff,7,7);plaza.castShadow=false;this.scene.add(plaza);this.ring(12.4,0xe1dac2,.09,0,-22);this.ring(4.5,0xd5d5af,.075,0,-22);
  const town=this.cyl(12,12,.1,0xada58c,0,.04,47,40);town.material=this.surface('road',0xffffff,6,6);town.castShadow=false;this.scene.add(town);
  const shore=this.cyl(18,18,.08,0xa0a591,51,.04,64,40);shore.scale.z=.77;shore.castShadow=false;this.scene.add(shore);
  const lake=this.cyl(16.7,16.7,.09,0x4cafbc,51,.10,64,48);lake.scale.z=.77;lake.material=this.material(0x55b9c7,{metalness:.55,roughness:.2,transparent:true,opacity:.88});lake.castShadow=false;this.scene.add(lake);this.block(51,64,27,18);
  for(let i=0;i<6;i++){const water=this.ring(3+i*2,0xa4d8d8,.035,51,64);water.scale.y=.77;water.material.opacity=.16;this.decorations.push(water);}
  for(let i=0;i<32;i++){const angle=i/32*TAU;const d=147+this.random()*15;const h=14+this.random()*40;const mountain=this.mesh(new THREE.ConeGeometry(19+this.random()*16,h,7),0x83a8bf,Math.sin(angle)*d,h/2-2,Math.cos(angle)*d);mountain.rotation.y=this.random()*TAU;mountain.castShadow=false;this.scene.add(mountain);}
 }
 house(x,z,w=8,d=8,h=5,roof=0x466875){return createHouse(this,x,z,w,d,h,roof);}
 tower(x,z,height=24,r=3,roof=0x436c83){const g=new THREE.Group();g.position.set(x,0,z);g.add(this.cyl(r,r*1.12,height,0xf0dfb9,0,height/2,0,16));g.add(this.cyl(r*1.13,r*1.13,.6,0x8caca5,0,height*.3,0,10));g.add(this.cyl(r*1.18,r*1.18,.6,0x8caca5,0,height*.75,0,10));g.add(this.mesh(new THREE.ConeGeometry(r*1.6,8,20),roof,0,height+3.8,0));g.add(this.cyl(.10,.10,3,0xd4b96e,0,height+9,0));for(let i=0;i<5;i++){const a=i/5*TAU;const win=this.box(.75,3,.18,0xffda8e,Math.sin(a)*(r+.02),height*.72,Math.cos(a)*(r+.02));win.rotation.y=a;g.add(win);}g.children[0].material=this.surface('stone',0xffffff,3,height/5);g.children[3].material=this.surface('roof',0xffffff,3,2);for(const y of [height*.30,height*.75,height]){const rim=this.mesh(new THREE.TorusGeometry(r*1.14,.07,4,40),0xead394,0,y,0);rim.rotation.x=Math.PI/2;g.add(rim);}this.scene.add(g);this.block(x,z,r*2,r*2,height+8);return g;}
 arch(x,z,r=5,h=10,color=0xbec4ae,rotation=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rotation;g.add(this.box(1.2,h,1.6,color,-r,h/2,0));g.add(this.box(1.2,h,1.6,color,r,h/2,0));const arc=this.mesh(new THREE.TorusGeometry(r,.65,6,24,Math.PI),color,0,h,0);g.add(arc);for(const side of [-1,1])g.add(this.box(2,.6,2.3,0x98aba0,side*r,.4,0));this.scene.add(g);return g;}
 buildWorld(){
  this.house(-20,44,10,8,5.5);this.house(-31,61,8,7,5,0x6f7977);this.house(22,63,11,9,5.2,0x867a68);this.house(24,36,8,8,5,0x526c70);this.house(-13,73,8,9,5,0x867a68);
  const well=this.mesh(new THREE.CylinderGeometry(1.7,1.8,1.1,24,1,true),0xcec29f,0,.6,46,{side:THREE.DoubleSide});this.scene.add(well);const rim=this.mesh(new THREE.TorusGeometry(1.7,.16,6,36),0xeee0b7,0,1.15,46);rim.rotation.x=-Math.PI/2;this.scene.add(rim);const water=this.cyl(1.36,1.36,.1,0x3d858d,0,.83,46,24);this.scene.add(water);this.ring(2.4,0xddc47b,.04,0,46);
  const hall=this.house(0,-49,30,17,13,0x385f76);hall.children[2].material=this.material(0x9ab5aa);this.tower(-19,-42,26,3.1);this.tower(19,-42,26,3.1);this.tower(0,-55,35,4.4);this.arch(0,-36,5,6);this.block(-5,-36,1.2,1.6);this.block(5,-36,1.2,1.6);
  for(const side of [-1,1]){for(let i=0;i<4;i++){const x=side*(7.4+i*2.7);const m=this.box(1.3,6,.3,0xdbc486,x,8,-40.4);this.scene.add(m);}for(let z=-31;z<=-10;z+=8){this.lantern(side*14,z);}}
  const focus=new THREE.Group();focus.position.set(0,0,-22);focus.add(this.cyl(1.5,1.8,.65,0x6b8b85,0,.36,0));const crystal=this.mesh(new THREE.OctahedronGeometry(.8),0x91dfd9,0,2,0,{emissive:0x55a7a9,emissiveIntensity:.7,metalness:.4,roughness:.2});focus.add(crystal);this.floaters.push(crystal);this.scene.add(focus);this.objects.push({id:'focus',name:'Trial focus',x:0,z:-22,kind:'focus',mesh:focus});
  for(const [i,z] of [34,21,8].entries()){const x=i%2?-4.2:4.2;const g=new THREE.Group();g.position.set(x,0,z);g.add(this.cyl(.72,.95,.8,0x71867a,0,.4,0));g.add(this.cyl(.2,.4,1.9,0x738579,0,1.3,0));g.add(this.cyl(.8,.6,.3,0xbfb085,0,2.1,0));const flame=this.mesh(this.flameGeometry(.44,1.05),0x698d91,0,2.65,0,{emissive:0x356268,emissiveIntensity:.3});g.add(flame);this.scene.add(g);this.objects.push({id:`light${i}`,name:'Unlit waylight',kind:'waylight',x,z,mesh:g,flame});}
  this.tower(-60,-32,11,3.2,0x5c7679);for(let i=0;i<8;i++){const b=this.box(1.4+this.random(),.6+this.random(),1.4,0x9eaa99,-60+(this.random()-.5)*15,.4,-30+(this.random()-.5)*13);b.rotation.y=this.random()*TAU;this.scene.add(b);}const journal=this.box(.8,.16,.65,0xdac794,-56,.7,-27);this.scene.add(journal);this.objects.push({id:'record',name:'Keeper’s journal',kind:'record',x:-56,z:-27,mesh:journal});
  this.arch(66,-53,4.3,5.8,0x8a9b94);this.ring(5.7,0xaaacd3,.13,66,-59);const arena=this.cyl(16,16,.15,0x536574,66,.08,-78,48);arena.castShadow=false;this.scene.add(arena);this.ring(14.8,0x9da3b4,.10,66,-78);for(let i=0;i<9;i++){const a=i/9*TAU;const x=66+Math.sin(a)*16,z=-78+Math.cos(a)*16;this.scene.add(this.cyl(.6,.9,6+this.random()*4,0x849998,x,3.3,z));}
  const seal=this.mesh(new THREE.CircleGeometry(4.2,48),0x736498,66,4,-53,{transparent:true,opacity:.43,emissive:0x4e3973,emissiveIntensity:.5,side:THREE.DoubleSide});this.scene.add(seal);this.objects.push({id:'crypt',name:'Door of the Sunken Choir',kind:'crypt',x:66,z:-49,mesh:seal});
  for(const [i,sp] of ['tinder','mend','stoneward'].entries()){const x=58+i*8,z=-66;const g=new THREE.Group();g.position.set(x,0,z);g.add(this.cyl(.9,1.3,1.3,0x7e8c85,0,.65,0));const c=this.mesh(new THREE.OctahedronGeometry(.5),[0xc77a4e,0x6dbbaa,0xc3b786][i],0,2.2,0);g.add(c);this.floaters.push(c);this.scene.add(g);this.objects.push({id:`rune${i}`,name:['The waking flame','The naming water','The remembering stone'][i],x,z,kind:'rune',spell:sp,mesh:g,flame:c});}
  const gate=this.arch(0,-101,6.2,9,0xa6b8ac);const outer=this.mesh(new THREE.TorusGeometry(7.3,.17,8,80),0xdfc784,0,9,-101);this.scene.add(outer);const disc=this.mesh(new THREE.CircleGeometry(5.6,64),0x618d97,0,8.5,-101,{transparent:true,opacity:.22,emissive:0x588184,emissiveIntensity:.8,side:THREE.DoubleSide});this.scene.add(disc);this.objects.push({id:'gate',name:'The Fifth-Year Gate',kind:'gate',x:0,z:-96,mesh:gate,flame:disc});this.ring(9,0xdbbc79,.10,0,-101);
  for(let i=0;i<6;i++){const m=this.box(2.2,1.2,2.2,0xadc1b3,Math.sin(i/6*TAU)*9,16+Math.sin(i)*2,-101+Math.cos(i/6*TAU)*3);m.rotation.z=i*.3;this.scene.add(m);this.floaters.push(m);}
  for(const n of NPCS){const mesh=this.character(n.color,n.hair,false,n.id);mesh.position.set(n.x,0,n.z);mesh.rotation.y=this.random()*TAU;this.scene.add(mesh);this.npcs.push({...n,mesh});}
  const camp=this.mesh(this.flameGeometry(.55,1.3),0xffd18d,-5,.7,54,{emissive:0xff8822,emissiveIntensity:1.6});this.scene.add(camp);this.floaters.push(camp);this.objects.push({id:'camp',name:'Hearthstone · rest',kind:'camp',x:-5,z:54,mesh:camp});this.ring(1.5,0xd5ac65,.1,-5,54);
  for(let i=0;i<11;i++){const x=i<5?25+i*5:-40-i*3,z=i<5?62+i%2*8:12-i*4;const g=new THREE.Group();g.position.set(x,0,z);for(let j=0;j<4;j++){const flower=this.mesh(new THREE.IcosahedronGeometry(.16,0),0xb9d4e9,(j%2)*.4,.65,(j/2|0)*.4);g.add(flower);}g.add(this.cyl(.1,.14,.65,0x446f53,0,.32,0,5));this.scene.add(g);this.objects.push({id:`herb${i}`,name:'Moon flax',kind:'herb',x,z,mesh:g});}
  for(const [x,z] of [[-8,35],[8,23],[-9,10],[16,47],[-16,37],[-28,54],[34,24],[47,16],[62,-14],[66,-37]])this.lantern(x,z);
 }
 lantern(x,z){const g=new THREE.Group();g.position.set(x,0,z);g.add(this.cyl(.11,.16,3.1,0x4e625b,0,1.5,0));g.add(this.box(.65,.8,.65,0xe8bd7d,0,3.1,0));g.add(this.mesh(new THREE.ConeGeometry(.59,.5,4),0x496661,0,3.8,0));this.scene.add(g);}
 buildNature(){createNature(this);}
 buildSky(){createSky(this);}
 character(color,hair=0xe3d8c2,player=false,id=""){const g=createCharacter(this,color,hair,player,id);return this.renderer.isSoftwareRenderer?g:batchActor(g);}
 creature(kind){const g=createCreature(this,kind);return this.renderer.isSoftwareRenderer?g:batchActor(g);}
 flameGeometry(r,h){return new THREE.LatheGeometry([new THREE.Vector2(0,0),new THREE.Vector2(r*.7,h*.12),new THREE.Vector2(r,h*.30),new THREE.Vector2(r*.5,h*.60),new THREE.Vector2(r*.25,h*.83),new THREE.Vector2(0,h)],12);}
 burst(x,y,z,color=0xffc178,count=18){count=Math.min(Math.ceil(count*(this.performanceProfile?.particles||.65)),Math.max(0,96-this.fx.length));for(let i=0;i<count;i++){const m=new THREE.Mesh(this.particleGeometry,new THREE.MeshBasicMaterial({color,transparent:true,opacity:1}));m.scale.set(.55,1.7,.55);m.rotation.z=Math.random()*TAU;m.position.set(x,y,z);this.scene.add(m);const a=Math.random()*TAU,s=2+Math.random()*5;this.fx.push({mesh:m,velocity:new THREE.Vector3(Math.cos(a)*s,Math.random()*4,Math.sin(a)*s),life:.45+Math.random()*.5,max:1});}}
 bolt(from,to,color){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.20,1),new THREE.MeshBasicMaterial({color}));m.position.copy(from);this.scene.add(m);this.fx.push({mesh:m,target:to.clone(),life:.32,max:.32});}
 updateEffects(dt,t){
  if(this.castPose>0){this.castPose=Math.max(0,this.castPose-dt*1.4);this.player.userData.rightArm.rotation.x=-Math.sin(this.castPose*Math.PI)*1.3;this.player.userData.staff.rotation.x=-Math.sin(this.castPose*Math.PI)*.25;}
  for(const n of this.npcs){n.mesh.userData.cape.rotation.x=-.045+Math.sin(t*1.3+n.x)*.03;n.mesh.userData.leftArm.rotation.x=Math.sin(t*1.1+n.x)*.025;}
  for(const b of this.banners)b.rotation.y=Math.sin(t*1.2+b.id)*.06;
  for(let i=this.sigilEffects.length-1;i>=0;i--){const f=this.sigilEffects[i];f.life-=dt;f.mesh.rotation.y+=dt*.8;const p=1-f.life/f.max;f.mesh.scale.setScalar(.75+Math.min(1,p*4)*.35);f.material.opacity=Math.max(0,Math.sin(p*Math.PI)*.85);if(f.life<=0){this.scene.remove(f.mesh);f.mesh.traverse(o=>o.geometry?.dispose());f.material.dispose();this.sigilEffects.splice(i,1);}}
 for(const o of this.floaters){if(o.userData.base===undefined)o.userData.base=o.position.y;o.position.y=o.userData.base+Math.sin(t*1.7+o.id)*.13;o.rotation.y+=dt*.55;}if(this.motes)this.motes.rotation.y=Math.sin(t*.01)*.08;for(let i=this.fx.length-1;i>=0;i--){const f=this.fx[i];f.life-=dt;if(f.target)f.mesh.position.lerp(f.target,Math.min(1,dt*12));else{f.mesh.position.addScaledVector(f.velocity,dt);f.velocity.y-=dt*5;f.mesh.material.opacity=Math.max(0,f.life/f.max);}if(f.life<=0){this.scene.remove(f.mesh);if(f.mesh.geometry!==this.particleGeometry)f.mesh.geometry.dispose();f.mesh.material.dispose();this.fx.splice(i,1);}}}
 resize(){const c=this.renderer.domElement,w=c.clientWidth||window.innerWidth,h=c.clientHeight||window.innerHeight;const p=this.performanceProfile||profile('balanced');this.renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,p.pixels,p.width/w,p.height/h)*(this.resolutionScale||1));this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 dispose(){this.scene.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});this.textures.forEach(t=>t.dispose());this.gradientMap.dispose();this.particleGeometry.dispose();this.renderer.dispose();}
}
